version: '3.9'
services:
  web:
    container_name: symfony-phar
    user: root
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www:rw
      #- vendor:/var/www/vendor
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true

volumes:
  vendor:
    driver: local